<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ejercicios_practicos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="ejercicios_practicos_files/libs/clipboard/clipboard.min.js"></script>
<script src="ejercicios_practicos_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ejercicios_practicos_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ejercicios_practicos_files/libs/quarto-html/popper.min.js"></script>
<script src="ejercicios_practicos_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ejercicios_practicos_files/libs/quarto-html/anchor.min.js"></script>
<link href="ejercicios_practicos_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ejercicios_practicos_files/libs/quarto-html/quarto-syntax-highlighting-b6a8276bf55561bdbc268162d41bd1f7.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ejercicios_practicos_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ejercicios_practicos_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ejercicios_practicos_files/libs/bootstrap/bootstrap-0c1e4c825cd24043973c3c8328bbeed5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="taller-2-cálculo-a-mano-de-los-índices-de-desarrollo-humano" class="level1">
<h1>Taller 2: Cálculo a mano de los Índices de Desarrollo Humano</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Indicaciones generales
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Lea con atención cada situación y resuelva los ejercicios a mano, mostrando todo el procedimiento en el espacio asignado. Utilice los topes (valores mínimos y máximos) y las fórmulas del recordatorio. Trabaje con cuatro decimales y, al final de cada ejercicio, escriba el resultado en el recuadro de respuesta y posteriormente su análisis.</li>
<li>Recuerde que cada índice se obtiene en dos pasos: primero normalice cada indicador a escala 0-1 y después agregue los índices con la media indicada.</li>
<li>Cuando un valor supere el máximo, recórtelo al máximo antes de calcular (por ejemplo, 18.9 años esperados se toman como 18).</li>
<li>Para el ingreso, utilice siempre el logaritmo natural (<span class="math inline">\(\ln\)</span>), no el valor en niveles.</li>
<li>Verifique que sus resultados queden siempre entre 0 y 1 (salvo el GDI, que es un cociente).</li>
</ul>
</div>
</div>
<section id="recordatorio-de-fórmulas-y-topes-de-referencia" class="level3">
<h3 class="anchored" data-anchor-id="recordatorio-de-fórmulas-y-topes-de-referencia">Recordatorio de fórmulas y topes de referencia</h3>
<ul>
<li><p><strong>Índice Dimensional General:</strong><br>
<span class="math display">\[I = \frac{\text{Valor Observado} - \text{Mínimo}}{\text{Máximo} - \text{Mínimo}}\]</span></p></li>
<li><p><strong>Índice de Ingreso (con escala logarítmica):</strong><br>
<span class="math display">\[I_{\text{Ingreso}} = \frac{\ln(\text{Valor}) - \ln(\text{Mínimo})}{\ln(\text{Máximo}) - \ln(\text{Mínimo})}\]</span></p></li>
<li><p><strong>Media Geométrica (3 dimensiones):</strong><br>
<span class="math display">\[HDI = \sqrt[3]{I_1 \times I_2 \times I_3}\]</span></p></li>
<li><p><strong>Media Armónica (2 dimensiones):</strong><br>
<span class="math display">\[HARM = \frac{2}{\frac{1}{G_1} + \frac{1}{G_2}}\]</span></p></li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indicador</th>
<th>Mínimo</th>
<th>Máximo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Esperanza de vida (años)</td>
<td>20</td>
<td>85</td>
</tr>
<tr class="even">
<td>Esp. de vida — mujeres (GDI)</td>
<td>22.5</td>
<td>87.5</td>
</tr>
<tr class="odd">
<td>Esp. de vida — hombres (GDI)</td>
<td>17.5</td>
<td>82.5</td>
</tr>
<tr class="even">
<td>Años esperados de escolaridad</td>
<td>0</td>
<td>18</td>
</tr>
<tr class="odd">
<td>Años promedio de escolaridad</td>
<td>0</td>
<td>15</td>
</tr>
<tr class="even">
<td>INB per cápita (PPA $)</td>
<td>100</td>
<td>75 000</td>
</tr>
<tr class="odd">
<td>Emisiones de CO₂ per cápita (t)</td>
<td>0</td>
<td>76.61</td>
</tr>
<tr class="even">
<td>Huella material per cápita (t)</td>
<td>0</td>
<td>90.27</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="ejercicio-1.-índice-de-desarrollo-humano-hdi" class="level2">
<h2 class="anchored" data-anchor-id="ejercicio-1.-índice-de-desarrollo-humano-hdi">Ejercicio 1. Índice de Desarrollo Humano (HDI)</h2>
<p>Calcule el HDI de los dos países a partir de los siguientes datos. Obtenga primero los tres índices dimensionales (salud, educación e ingreso) y luego combínelos con la media geométrica.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>País</th>
<th>Esp. vida (años)</th>
<th>Años esperados</th>
<th>Años promedio</th>
<th>INB per cápita (PPA $)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>País X</td>
<td>68.5</td>
<td>13.2</td>
<td>8.7</td>
<td>12 500</td>
</tr>
<tr class="even">
<td>País Y</td>
<td>80.1</td>
<td>16.5</td>
<td>12.3</td>
<td>45 000</td>
</tr>
</tbody>
</table>
<section id="desarrollo-paso-a-paso" class="level3">
<h3 class="anchored" data-anchor-id="desarrollo-paso-a-paso">Desarrollo paso a paso</h3>
<section id="desarrollo-del-país-x" class="level4">
<h4 class="anchored" data-anchor-id="desarrollo-del-país-x">1. Desarrollo del País X</h4>
<ul>
<li><strong>Índice de Salud (<span class="math inline">\(I_{\text{salud}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{salud}} = \frac{68.5 - 20}{85 - 20} = \frac{48.5}{65} \approx 0.7462\]</span></p>
<ul>
<li><strong>Índice de Educación (<span class="math inline">\(I_{\text{educ}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{educ}} = \frac{\frac{13.2}{18} + \frac{8.7}{15}}{2} = \frac{0.7333 + 0.5800}{2} = \frac{1.3133}{2} \approx 0.6567\]</span></p>
<ul>
<li><strong>Índice de Ingreso (<span class="math inline">\(I_{\text{INB}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{INB}} = \frac{\ln(12500) - \ln(100)}{\ln(75000) - \ln(100)} = \frac{9.4335 - 4.6052}{11.2252 - 4.6052} = \frac{4.8283}{6.6201} \approx 0.7293\]</span></p>
<ul>
<li><strong>Índice de Desarrollo Humano (HDI):</strong></li>
</ul>
<p><span class="math display">\[HDI_X = \sqrt[3]{0.7462 \times 0.6567 \times 0.7293} = \sqrt[3]{0.3574} \approx 0.7096\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip Metodológico: Media Geométrica vs Aritmética
</div>
</div>
<div class="callout-body-container callout-body">
<p>La media geométrica multiplica los valores antes de aplicar la raíz cúbica. Esto significa que <strong>si un índice baja mucho, arrastra con más fuerza el promedio general</strong>. No hay sustitución perfecta.</p>
</div>
</div>
</section>
<section id="desarrollo-del-país-y" class="level4">
<h4 class="anchored" data-anchor-id="desarrollo-del-país-y">2. Desarrollo del País Y</h4>
<ul>
<li><strong>Índice de Salud (<span class="math inline">\(I_{\text{salud}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{salud}} = \frac{80.1 - 20}{85 - 20} = \frac{60.1}{65} \approx 0.9246\]</span></p>
<ul>
<li><strong>Índice de Educación (<span class="math inline">\(I_{\text{educ}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{educ}} = \frac{\frac{16.5}{18} + \frac{12.3}{15}}{2} = \frac{0.9167 + 0.8200}{2} = \frac{1.7367}{2} \approx 0.8683\]</span></p>
<ul>
<li><strong>Índice de Ingreso (<span class="math inline">\(I_{\text{INB}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{INB}} = \frac{\ln(45000) - \ln(100)}{\ln(75000) - \ln(100)} = \frac{10.7144 - 4.6052}{11.2252 - 4.6052} = \frac{6.1092}{6.6201} \approx 0.9228\]</span></p>
<ul>
<li><strong>Índice de Desarrollo Humano (HDI):</strong></li>
</ul>
<p><span class="math display">\[HDI_Y = \sqrt[3]{0.9246 \times 0.8683 \times 0.9228} = \sqrt[3]{0.7408} \approx 0.9049\]</span></p>
</section>
</section>
<section id="respuestas-y-cuadro-resumen" class="level3">
<h3 class="anchored" data-anchor-id="respuestas-y-cuadro-resumen">Respuestas y Cuadro Resumen</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>País</th>
<th><span class="math inline">\(I_{\text{salud}}\)</span></th>
<th><span class="math inline">\(I_{\text{educación}}\)</span></th>
<th><span class="math inline">\(I_{\text{INB}}\)</span></th>
<th>HDI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>País X</strong></td>
<td>0.7462</td>
<td>0.6567</td>
<td>0.7293</td>
<td><strong>0.7096</strong></td>
</tr>
<tr class="even">
<td><strong>País Y</strong></td>
<td>0.9246</td>
<td>0.8683</td>
<td>0.9228</td>
<td><strong>0.9049</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Análisis comparativo del IDH
</div>
</div>
<div class="callout-body-container callout-body">
<p>El <strong>País Y</strong> presenta un nivel de desarrollo humano <strong>Muy Alto</strong> (<span class="math inline">\(HDI \ge 0.800\)</span>), impulsado por indicadores robustos en salud (esperanza de vida que supera los 80 años) y un elevado nivel de ingresos e instrucción. Por otro lado, el <strong>País X</strong> se clasifica en la categoría de desarrollo humano <strong>Alto</strong> (<span class="math inline">\(0.700 \le HDI &lt; 0.800\)</span>). El factor más crítico para el País X es la <strong>educación (0.6567)</strong>, mostrando la necesidad prioritaria de invertir en infraestructura escolar y retención académica.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="ejercicio-2.-hdi-ajustado-por-desigualdad-ihdi" class="level2">
<h2 class="anchored" data-anchor-id="ejercicio-2.-hdi-ajustado-por-desigualdad-ihdi">Ejercicio 2. HDI ajustado por desigualdad (IHDI)</h2>
<p>El País V tiene los indicadores que se muestran abajo y las siguientes desigualdades de Atkinson: salud 12 %, educación 15 % e ingreso 25 %. Calcule el HDI, luego ajuste cada dimensión multiplicándola por <span class="math inline">\((1 - A)\)</span>, obtenga el IHDI y, por último, la pérdida por desigualdad.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>País</th>
<th>Esp. vida</th>
<th>Años esperados</th>
<th>Años promedio</th>
<th>INB (PPA $)</th>
<th>A salud</th>
<th>A educ.</th>
<th>A ingreso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>País V</td>
<td>72</td>
<td>13</td>
<td>9</td>
<td>11 000</td>
<td>12 %</td>
<td>15 %</td>
<td>25 %</td>
</tr>
</tbody>
</table>
<section id="desarrollo-paso-a-paso-1" class="level3">
<h3 class="anchored" data-anchor-id="desarrollo-paso-a-paso-1">Desarrollo paso a paso</h3>
<p><strong>1. Cálculo del HDI base (sin ajustar):</strong></p>
<ul>
<li><span class="math inline">\(I_{\text{salud}} = \frac{72 - 20}{85 - 20} = \frac{52}{65} = 0.8000\)</span></li>
<li><span class="math inline">\(I_{\text{educ}} = \frac{\frac{13}{18} + \frac{9}{15}}{2} = \frac{0.7222 + 0.6000}{2} \approx 0.6611\)</span></li>
<li><span class="math inline">\(I_{\text{INB}} = \frac{\ln(11000) - \ln(100)}{\ln(75000) - \ln(100)} = \frac{9.3057 - 4.6052}{11.2252 - 4.6052} \approx 0.7100\)</span></li>
<li><span class="math inline">\(HDI = \sqrt[3]{0.8000 \times 0.6611 \times 0.7100} = \sqrt[3]{0.3755} \approx 0.7215\)</span></li>
</ul>
<p><strong>2. Ajuste dimensional por coeficiente de Atkinson <span class="math inline">\((1 - A)\)</span>:</strong></p>
<ul>
<li><p><strong>Salud ajustada (<span class="math inline">\(I_{\text{salud}}^*\)</span>):</strong><br>
<span class="math display">\[I_{\text{salud}}^* = 0.8000 \times (1 - 0.12) = 0.7040\]</span></p></li>
<li><p><strong>Educación ajustada (<span class="math inline">\(I_{\text{educ}}^*\)</span>):</strong><br>
<span class="math display">\[I_{\text{educ}}^* = 0.6611 \times (1 - 0.15) \approx 0.5619\]</span></p></li>
<li><p><strong>Ingreso ajustado (<span class="math inline">\(I_{\text{INB}}^*\)</span>):</strong><br>
<span class="math display">\[I_{\text{INB}}^* = 0.7100 \times (1 - 0.25) \approx 0.5325\]</span></p></li>
</ul>
<p><strong>3. Cálculo del IHDI:</strong></p>
<p><span class="math display">\[IHDI = \sqrt[3]{0.7040 \times 0.5619 \times 0.5325} = \sqrt[3]{0.2106} \approx 0.5950\]</span></p>
<p><strong>4. Cálculo de la pérdida porcentual por desigualdad:</strong></p>
<p><span class="math display">\[\text{Pérdida} = 100 \times \left(1 - \frac{IHDI}{HDI}\right) = 100 \times \left(1 - \frac{0.5950}{0.7215}\right) \approx 17.5312\%\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip para el Examen: El factor de descuento
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para aplicar la desigualdad de Atkinson, recuerda que multiplicas por <span class="math inline">\((1 - A)\)</span>. Por ejemplo, si la desigualdad de ingresos es del 25%, el descuento neto es dejar solo el 75% del índice original (<span class="math inline">\(1 - 0.25 = 0.75\)</span>).</p>
</div>
</div>
</section>
<section id="respuestas" class="level3">
<h3 class="anchored" data-anchor-id="respuestas">Respuestas</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>HDI</th>
<th>IHDI</th>
<th>Pérdida por desigualdad (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>0.7215</strong></td>
<td><strong>0.5950</strong></td>
<td><strong>17.5312%</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Análisis de Equidad Social
</div>
</div>
<div class="callout-body-container callout-body">
<p>El País V pierde un <strong>17.53%</strong> de su potencial de desarrollo a causa de las disparidades internas. El principal factor distorsionador es la <strong>desigualdad en ingresos (25%)</strong>, que deprime el subíndice económico a 0.5325. Esta desigualdad provoca que la clasificación real del país descienda desde un nivel <strong>Alto</strong> (0.7215) a un nivel <strong>Medio</strong> (0.5950).</p>
</div>
</div>
<hr>
</section>
</section>
<section id="ejercicio-3.-índice-de-desarrollo-de-género-gdi" class="level2">
<h2 class="anchored" data-anchor-id="ejercicio-3.-índice-de-desarrollo-de-género-gdi">Ejercicio 3. Índice de Desarrollo de Género (GDI)</h2>
<p>Calcule el HDI separado para mujeres y para hombres del País Z, y obtenga el GDI como el cociente entre ambos. Tenga presente que la esperanza de vida usa topes distintos según el sexo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Grupo</th>
<th>Esp. vida</th>
<th>Años esperados</th>
<th>Años promedio</th>
<th>Ingreso estimado (PPA $)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mujeres</td>
<td>78</td>
<td>14.5</td>
<td>11</td>
<td>6 000</td>
</tr>
<tr class="even">
<td>Hombres</td>
<td>73</td>
<td>13.8</td>
<td>10.5</td>
<td>22 000</td>
</tr>
</tbody>
</table>
<section id="desarrollo-paso-a-paso-2" class="level3">
<h3 class="anchored" data-anchor-id="desarrollo-paso-a-paso-2">Desarrollo paso a paso</h3>
<section id="cálculo-para-mujeres-hdi_f" class="level4">
<h4 class="anchored" data-anchor-id="cálculo-para-mujeres-hdi_f">1. Cálculo para Mujeres (<span class="math inline">\(HDI_F\)</span>)</h4>
<ul>
<li><strong>Salud (<span class="math inline">\(I_{\text{salud}, F}\)</span>):</strong> (Tope Mujeres: mín 22.5, máx 87.5)</li>
</ul>
<p><span class="math display">\[I_{\text{salud}, F} = \frac{78 - 22.5}{87.5 - 22.5} = \frac{55.5}{65} \approx 0.8538\]</span></p>
<ul>
<li><strong>Educación (<span class="math inline">\(I_{\text{educ}, F}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{educ}, F} = \frac{\frac{14.5}{18} + \frac{11}{15}}{2} = \frac{0.8056 + 0.7333}{2} \approx 0.7694\]</span></p>
<ul>
<li><strong>Ingreso (<span class="math inline">\(I_{\text{INB}, F}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{INB}, F} = \frac{\ln(6000) - \ln(100)}{\ln(75000) - \ln(100)} = \frac{4.0943}{6.6201} \approx 0.6185\]</span></p>
<ul>
<li><strong>HDI Femenino (<span class="math inline">\(HDI_F\)</span>):</strong></li>
</ul>
<p><span class="math display">\[HDI_F = \sqrt[3]{0.8538 \times 0.7694 \times 0.6185} \approx 0.7407\]</span></p>
</section>
<section id="cálculo-para-hombres-hdi_m" class="level4">
<h4 class="anchored" data-anchor-id="cálculo-para-hombres-hdi_m">2. Cálculo para Hombres (<span class="math inline">\(HDI_M\)</span>)</h4>
<ul>
<li><strong>Salud (<span class="math inline">\(I_{\text{salud}, H}\)</span>):</strong> (Tope Hombres: mín 17.5, máx 82.5)</li>
</ul>
<p><span class="math display">\[I_{\text{salud}, H} = \frac{73 - 17.5}{82.5 - 17.5} = \frac{55.5}{65} \approx 0.8538\]</span></p>
<ul>
<li><strong>Educación (<span class="math inline">\(I_{\text{educ}, H}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{educ}, H} = \frac{\frac{13.8}{18} + \frac{10.5}{15}}{2} = \frac{0.7667 + 0.7000}{2} \approx 0.7333\]</span></p>
<ul>
<li><strong>Ingreso (<span class="math inline">\(I_{\text{INB}, H}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{INB}, H} = \frac{\ln(22000) - \ln(100)}{\ln(75000) - \ln(100)} = \frac{5.3936}{6.6201} \approx 0.8147\]</span></p>
<ul>
<li><strong>HDI Masculino (<span class="math inline">\(HDI_M\)</span>):</strong></li>
</ul>
<p><span class="math display">\[HDI_M = \sqrt[3]{0.8538 \times 0.7333 \times 0.8147} \approx 0.7990\]</span></p>
</section>
<section id="cálculo-del-gdi" class="level4">
<h4 class="anchored" data-anchor-id="cálculo-del-gdi">3. Cálculo del GDI</h4>
<p><span class="math display">\[GDI = \frac{HDI_F}{HDI_M} = \frac{0.7407}{0.7990} \approx 0.9270\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip Mnemotécnico: Topes del GDI
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para recordar los topes de esperanza de vida en GDI: <strong>las mujeres viven estadísticamente más</strong>, por lo que sus límites se desplazan <strong>5 años hacia arriba</strong> (22.5 a 87.5) frente a los hombres (17.5 a 82.5). El promedio aritmético de ambos vuelve a ser la escala estándar general (20 y 85).</p>
</div>
</div>
</section>
</section>
<section id="respuestas-1" class="level3">
<h3 class="anchored" data-anchor-id="respuestas-1">Respuestas</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>HDI mujeres</th>
<th>HDI hombres</th>
<th>GDI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>0.7407</strong></td>
<td><strong>0.7990</strong></td>
<td><strong>0.9270</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Análisis de Disparidad de Género
</div>
</div>
<div class="callout-body-container callout-body">
<p>El GDI de <strong>0.9270</strong> indica una disparidad de género significativa en perjuicio de las mujeres (desviación superior al 7% respecto a la paridad). El análisis revela que, aunque no hay brechas en salud (ambos subíndices en 0.8538) y la educación de las mujeres es discretamente superior, la brecha de ingresos (donde los hombres ganan <strong>3.6 veces</strong> más que las mujeres) es el factor determinante detrás del rezago del desarrollo femenino en el País Z.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="ejercicio-4.-índice-de-desigualdad-de-género-gii" class="level2">
<h2 class="anchored" data-anchor-id="ejercicio-4.-índice-de-desigualdad-de-género-gii">Ejercicio 4. Índice de Desigualdad de Género (GII)</h2>
<p>Calcule el GII del País W. Recuerde que el índice de salud reproductiva de los hombres se fija en 1, que la razón de mortalidad materna se recorta entre 10 y 1000, y que el resultado final se obtiene comparando la media armónica de ambos sexos con la referencia de igualdad.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indicador</th>
<th>Mujeres</th>
<th>Hombres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Razón de mortalidad materna (por 100 000)</td>
<td>120</td>
<td>—</td>
</tr>
<tr class="even">
<td>Tasa de fecundidad adolescente (por 1 000)</td>
<td>60</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Escaños en el parlamento (%)</td>
<td>28</td>
<td>72</td>
</tr>
<tr class="even">
<td>Población con secundaria (%)</td>
<td>55</td>
<td>60</td>
</tr>
<tr class="odd">
<td>Tasa de participación laboral (%)</td>
<td>50</td>
<td>75</td>
</tr>
</tbody>
</table>
<section id="desarrollo-paso-a-paso-3" class="level3">
<h3 class="anchored" data-anchor-id="desarrollo-paso-a-paso-3">Desarrollo paso a paso</h3>
<section id="índices-dimensionales-femeninos-f" class="level4">
<h4 class="anchored" data-anchor-id="índices-dimensionales-femeninos-f">1. Índices Dimensionales Femeninos (F)</h4>
<ul>
<li><strong>Salud (<span class="math inline">\(G_{\text{sal}, F}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[G_{\text{sal}, F} = \sqrt{\frac{10}{120} \times \frac{1}{60}} = \sqrt{0.0833 \times 0.0167} \approx 0.0373\]</span></p>
<ul>
<li><strong>Empoderamiento (<span class="math inline">\(G_{\text{emp}, F}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[G_{\text{emp}, F} = \sqrt{0.28 \times 0.55} = \sqrt{0.1540} \approx 0.3924\]</span></p>
<ul>
<li><strong>Mercado Laboral (<span class="math inline">\(G_{\text{lab}, F}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[G_{\text{lab}, F} = \frac{50}{100} = 0.5000\]</span></p>
<ul>
<li><strong>Índice Agregado Femenino (<span class="math inline">\(G_F\)</span>):</strong></li>
</ul>
<p><span class="math display">\[G_F = \sqrt[3]{0.0373 \times 0.3924 \times 0.5000} = \sqrt[3]{0.007318} \approx 0.1941\]</span></p>
</section>
<section id="índices-dimensionales-masculinos-m" class="level4">
<h4 class="anchored" data-anchor-id="índices-dimensionales-masculinos-m">2. Índices Dimensionales Masculinos (M)</h4>
<ul>
<li><strong>Salud (<span class="math inline">\(G_{\text{sal}, M}\)</span>):</strong> Se fija en <strong>1.0000</strong> por definición metodológica.</li>
<li><strong>Empoderamiento (<span class="math inline">\(G_{\text{emp}, M}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[G_{\text{emp}, M} = \sqrt{0.72 \times 0.60} = \sqrt{0.4320} \approx 0.6573\]</span></p>
<ul>
<li><strong>Mercado Laboral (<span class="math inline">\(G_{\text{lab}, M}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[G_{\text{lab}, M} = \frac{75}{100} = 0.7500\]</span></p>
<ul>
<li><strong>Índice Agregado Masculino (<span class="math inline">\(G_M\)</span>):</strong></li>
</ul>
<p><span class="math display">\[G_M = \sqrt[3]{1.0000 \times 0.6573 \times 0.7500} = \sqrt[3]{0.4930} \approx 0.7900\]</span></p>
</section>
<section id="media-armónica-harm" class="level4">
<h4 class="anchored" data-anchor-id="media-armónica-harm">3. Media Armónica (<span class="math inline">\(HARM\)</span>)</h4>
<p><span class="math display">\[HARM = \frac{2}{\frac{1}{G_F} + \frac{1}{G_M}} = \frac{2}{\frac{1}{0.1941} + \frac{1}{0.7900}} = \frac{2}{5.1520 + 1.2658} \approx 0.3116\]</span></p>
</section>
<section id="referencia-de-igualdad-ref" class="level4">
<h4 class="anchored" data-anchor-id="referencia-de-igualdad-ref">4. Referencia de Igualdad (<span class="math inline">\(Ref\)</span>)</h4>
<p><span class="math display">\[Ref_{\text{sal}} = \frac{0.0373 + 1.0000}{2} = 0.5187\]</span> <span class="math display">\[Ref_{\text{emp}} = \frac{0.3924 + 0.6573}{2} = 0.5249\]</span> <span class="math display">\[Ref_{\text{lab}} = \frac{0.5000 + 0.7500}{2} = 0.6250\]</span> <span class="math display">\[Ref = \sqrt[3]{0.5187 \times 0.5249 \times 0.6250} = \sqrt[3]{0.1701} \approx 0.5541\]</span></p>
</section>
<section id="índice-de-desigualdad-de-género-gii" class="level4">
<h4 class="anchored" data-anchor-id="índice-de-desigualdad-de-género-gii">5. Índice de Desigualdad de Género (GII)</h4>
<p><span class="math display">\[GII = 1 - \frac{HARM}{Ref} = 1 - \frac{0.3116}{0.5541} \approx 0.4376\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip para el Examen: ¿Qué representa el GII?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A diferencia de otros índices, <strong>un GII más alto es peor</strong>. 0 representa igualdad perfecta y 1 desigualdad absoluta. Este índice mide la <strong>pérdida de desarrollo humano potencial</strong> debido a la discriminación de género.</p>
</div>
</div>
</section>
</section>
<section id="respuestas-2" class="level3">
<h3 class="anchored" data-anchor-id="respuestas-2">Respuestas</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(G_F\)</span></th>
<th><span class="math inline">\(G_M\)</span></th>
<th>Media armónica</th>
<th>Referencia</th>
<th>GII</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1941</td>
<td>0.7900</td>
<td>0.3116</td>
<td>0.5541</td>
<td><strong>0.4376</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Análisis de Inequidad de Género
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un GII de <strong>0.4376 (43.76%)</strong> indica que el País W pierde casi la mitad de sus posibilidades de progreso debido a inequidades de género. El factor más alarmante es el subíndice de salud reproductiva de las mujeres (<span class="math inline">\(0.0373\)</span>), lastrado por una razón de mortalidad materna elevada y una tasa de fecundidad adolescente que limita las trayectorias educativas y profesionales de las jóvenes.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="ejercicio-5.-hdi-ajustado-por-presiones-planetarias-phdi" class="level2">
<h2 class="anchored" data-anchor-id="ejercicio-5.-hdi-ajustado-por-presiones-planetarias-phdi">Ejercicio 5. HDI ajustado por presiones planetarias (PHDI)</h2>
<p>Retome los países X e Y del Ejercicio 1 y descuente su nivel de desarrollo según sus presiones ambientales. Calcule el índice de CO₂ y el de huella material, promédielos para obtener el factor de ajuste y multiplíquelo por el HDI.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>País</th>
<th>HDI (Ejercicio 1)</th>
<th>CO₂ per cápita (t)</th>
<th>Huella material per cápita (t)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>País X</td>
<td>0.7096</td>
<td>5.2</td>
<td>9.8</td>
</tr>
<tr class="even">
<td>País Y</td>
<td>0.9049</td>
<td>11.4</td>
<td>25.6</td>
</tr>
</tbody>
</table>
<section id="desarrollo-paso-a-paso-4" class="level3">
<h3 class="anchored" data-anchor-id="desarrollo-paso-a-paso-4">Desarrollo paso a paso</h3>
<section id="desarrollo-del-país-x-1" class="level4">
<h4 class="anchored" data-anchor-id="desarrollo-del-país-x-1">1. Desarrollo del País X</h4>
<ul>
<li><strong>Índice de <span class="math inline">\(CO_2\)</span> (<span class="math inline">\(I_{CO_2}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{CO_2} = \frac{76.61 - 5.2}{76.61} = \frac{71.41}{76.61} \approx 0.9321\]</span></p>
<ul>
<li><strong>Índice de Huella Material (<span class="math inline">\(I_{\text{huella}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{huella}} = \frac{90.27 - 9.8}{90.27} = \frac{80.47}{90.27} \approx 0.8914\]</span></p>
<ul>
<li><strong>Factor de Ajuste:</strong></li>
</ul>
<p><span class="math display">\[\text{Factor}_X = \frac{0.9321 + 0.8914}{2} = 0.9118\]</span></p>
<ul>
<li><strong>PHDI del País X:</strong></li>
</ul>
<p><span class="math display">\[PHDI_X = 0.7096 \times 0.9118 \approx 0.6470\]</span></p>
</section>
<section id="desarrollo-del-país-y-1" class="level4">
<h4 class="anchored" data-anchor-id="desarrollo-del-país-y-1">2. Desarrollo del País Y</h4>
<ul>
<li><strong>Índice de <span class="math inline">\(CO_2\)</span> (<span class="math inline">\(I_{CO_2}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{CO_2} = \frac{76.61 - 11.4}{76.61} \approx 0.8512\]</span></p>
<ul>
<li><strong>Índice de Huella Material (<span class="math inline">\(I_{\text{huella}}\)</span>):</strong></li>
</ul>
<p><span class="math display">\[I_{\text{huella}} = \frac{90.27 - 25.6}{90.27} \approx 0.7164\]</span></p>
<ul>
<li><strong>Factor de Ajuste:</strong></li>
</ul>
<p><span class="math display">\[\text{Factor}_Y = \frac{0.8512 + 0.7164}{2} \approx 0.7838\]</span></p>
<ul>
<li><strong>PHDI del País Y:</strong></li>
</ul>
<p><span class="math display">\[PHDI_Y = 0.9049 \times 0.7838 \approx 0.7093\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip de Interpretación del PHDI
</div>
</div>
<div class="callout-body-container callout-body">
<p>El factor de ajuste del PHDI es <strong>menor mientras mayor sea la huella ecológica</strong>. Por eso la resta en el numerador es <span class="math inline">\(\text{Máximo} - \text{Valor}\)</span>, castigando a los países emisores. Si un país tiene cero emisiones y cero huella, su factor sería 1 (no sufre descuento).</p>
</div>
</div>
</section>
</section>
<section id="respuestas-3" class="level3">
<h3 class="anchored" data-anchor-id="respuestas-3">Respuestas</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>País</th>
<th><span class="math inline">\(I_{\text{CO₂}}\)</span></th>
<th><span class="math inline">\(I_{\text{huella}}\)</span></th>
<th>Factor</th>
<th>PHDI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>País X</strong></td>
<td>0.9321</td>
<td>0.8914</td>
<td>0.9118</td>
<td><strong>0.6470</strong></td>
</tr>
<tr class="even">
<td><strong>País Y</strong></td>
<td>0.8512</td>
<td>0.7164</td>
<td>0.7838</td>
<td><strong>0.7093</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Análisis de Sostenibilidad Ecológica
</div>
</div>
<div class="callout-body-container callout-body">
<p>El ajuste por presiones planetarias reduce el bienestar aparente de forma asimétrica. El <strong>País Y</strong> sufre una fuerte caída en su indicador (el factor de 0.7838 descuenta más del 21% de su desarrollo, bajando su PHDI a 0.7093) debido a su alto consumo material y emisiones. La brecha inicial entre el País Y y el País X se reduce drásticamente de <strong>0.1953</strong> (en el HDI tradicional) a apenas <strong>0.0623</strong> en el PHDI. Esto demuestra que los altos niveles de vida en el País Y se sostienen sobre una base ecológica insostenible.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="anexo-fórmulas-y-metodología-de-los-índices-del-pnud" class="level2">
<h2 class="anchored" data-anchor-id="anexo-fórmulas-y-metodología-de-los-índices-del-pnud">Anexo: Fórmulas y Metodología de los Índices del PNUD</h2>
<section id="normalización-general" class="level3">
<h3 class="anchored" data-anchor-id="normalización-general">1. Normalización General</h3>
<p><span class="math display">\[I_x = \frac{\text{Valor Observado} - \text{Mínimo}}{\text{Máximo} - \text{Mínimo}}\]</span> <em>Reescala cualquier indicador en un rango de 0 a 1.</em></p>
</section>
<section id="dimensión-de-ingreso" class="level3">
<h3 class="anchored" data-anchor-id="dimensión-de-ingreso">2. Dimensión de Ingreso</h3>
<p><span class="math display">\[I_{\text{Ingreso}} = \frac{\ln(INB) - \ln(100)}{\ln(75000) - \ln(100)}\]</span> <em>Usa logaritmo natural (<span class="math inline">\(\ln\)</span>) para reflejar que la utilidad marginal del ingreso disminuye a niveles elevados.</em></p>
</section>
<section id="ajuste-por-desigualdad-atkinson" class="level3">
<h3 class="anchored" data-anchor-id="ajuste-por-desigualdad-atkinson">3. Ajuste por Desigualdad (Atkinson)</h3>
<p><span class="math display">\[I^* = I \times (1 - A)\]</span> <em>Descuenta la desigualdad interna del país en cada componente.</em></p>
</section>
<section id="desigualdad-de-género-gii" class="level3">
<h3 class="anchored" data-anchor-id="desigualdad-de-género-gii">4. Desigualdad de Género (GII)</h3>
<p><span class="math display">\[GII = 1 - \frac{HARM}{Ref}\]</span> <em>Mide la disparidad entre la media armónica por sexo (<span class="math inline">\(HARM\)</span>) y la referencia de igualdad absoluta (<span class="math inline">\(Ref\)</span>).</em></p>
<hr>
</section>
</section>
<section id="plantillas-para-la-redacción-de-análisis-económico" class="level2">
<h2 class="anchored" data-anchor-id="plantillas-para-la-redacción-de-análisis-económico">Plantillas para la Redacción de Análisis Económico</h2>
<p>Estas plantillas normalizan la argumentación técnica para informes profesionales:</p>
<ul>
<li><strong>Para HDI:</strong> El país presenta un desarrollo <strong>[Muy Alto/Alto/Medio/Bajo]</strong> liderado por <strong>[Dimensión fuerte]</strong> (<span class="math inline">\([Subíndice]\)</span>) y limitado por <strong>[Dimensión débil]</strong> (<span class="math inline">\([Subíndice]\)</span>).</li>
<li><strong>Para IHDI:</strong> La desigualdad interna resta un <strong>[Pérdida %]</strong> del desarrollo humano potencial, siendo la brecha en <strong>[Dimensión]</strong> el principal catalizador de esta pérdida.</li>
<li><strong>Para GDI:</strong> Se observa una disparidad de género <strong>[Moderada/Severa]</strong> (<span class="math inline">\([GDI]\)</span>) impulsada mayoritariamente por una asimetría en <strong>[Ingreso/Educación]</strong> de <span class="math inline">\([Proporción]\)</span> veces a favor de los hombres.</li>
<li><strong>Para PHDI:</strong> La incorporación de presiones ambientales reduce un <strong>[Descuento %]</strong> del desarrollo debido a emisiones de <span class="math inline">\(CO_2\)</span> (<span class="math inline">\([CO_2 \text{ pc}]\)</span> t) y sobreconsumo material (<span class="math inline">\([Huella]\)</span> t), denotando un modelo de crecimiento ecológicamente insostenible.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>